---
- hosts: all
  become: true # sudo elevation
  tasks:

  - name: install apache and php package
    package: # generic module for package managers
      name:
        # variables defined in the inventory
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes