---
- hosts: all
  become: true # sudo elevation
  tasks:

  - name: update repository
    apt:
      update_cache: yes

  - name: remove apache2 package
    apt:
      name: apache2
      state: absent # remove

  - name: remove php support
    apt:
      name: libapache2-mod-php
      state: absent # remove